version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 654654570586.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-python-app:$IMAGE_TAG .
  post_build:
    commands:
      - echo Tagging and pushing image to ECR...
      - docker tag my-python-app:$IMAGE_TAG 654654570586.dkr.ecr.us-east-1.amazonaws.com/my-python-app:$IMAGE_TAG
      - docker push 654654570586.dkr.ecr.us-east-1.amazonaws.com/my-python-app:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
