version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 654654570586.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t doker-python-app .
      - docker tag doker-python-app:latest 654654570586.dkr.ecr.us-east-1.amazonaws.com/doker-python-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 654654570586.dkr.ecr.us-east-1.amazonaws.com/doker-python-app:latest
artifacts:
  files: '**/*'
