version: 0.2

env:
  secrets-manager:
    DOCKER_USERNAME: dockerHubCredentials:username
    DOCKER_PASSWORD: dockerHubCredentials:password

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t docker-python-app .
      - docker tag docker-python-app vikasy/docker-python-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Docker Hub...
      - docker push vikasy/docker-python-app:latest
