version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: dockerHubCredentials:username
    DOCKERHUB_PASSWORD: dockerHubCredentials:password

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t docker-python-app .
  post_build:
    commands:
      - echo Tagging and pushing the image...
      - docker tag docker-python-app vikasy/docker-python-app:latest
      - docker push vikasy/docker-python-app:latest

artifacts:
  files:
    - '**/*'
